import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'fleury.lol',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-neutral-800 text-neutral-300 p-2 flex justify-center">
        {children}
      </body>
    </html>
  );
}
